### PR TITLE
Glb zero chunk tests

### PR DESCRIPTION
**Pull request by Kh4n**
Added tests, removed some gitignore files

### CODE REVIEW

**Comment by syoyo** [comment]
@Kh4n Thanks! I did some investigation and did fixes, then confirmed all tests passes. Your PR removes toplevel `Makefile` for some reason, so I cannot do merge as is. I'll do some cherry-picking or copy-paste unit test code of this PR to my local branch.

**Comment by Kh4n** [comment]
Oops, had the wrong gitignore unignore path, the makefile is back

**Comment by Kh4n** [comment]
Sorry if the way I did this PR is inconvenient, I couldn't find a CONTRIBUTING so I just did things the way I am used to (aka new PR into your PR) 😅

**Comment by syoyo** [comment]
@Kh4n Thanks! Merged PR into https://github.com/syoyo/tinygltf/pull/382 . There was wrong inequality check when CHUNK1(BIN) is empty. Fix is all included to PR 382. Please try that PR again. Unit tests should all pass.

**Comment by Kh4n** [comment]
@syoyo  Looks all good to me! Thanks for this fix :)

**Pull request merged**
