### PR TITLE
Fix msvc build -- STRICT is a msvc macro name

### PR DESCRIPTION
**Pull request by nyalldawson**
Follow up https://github.com/syoyo/tinygltf/pull/445

### CODE REVIEW

**Comment by syoyo** [comment]
MSVC CI build passes. https://github.com/syoyo/tinygltf/pull/445

What is the error message?

**Comment by nyalldawson** [comment]
Sorry, it's actually the msys build which has issues with this name. See eg https://github.com/qgis/QGIS/actions/runs/6060705066/job/16445155328

**Comment by syoyo** [comment]
I see. it'd be better to add msys2 + MinGW(ucrt) CI to tinygltf's Github Actions before merging this PR.

**Comment by nyalldawson** [comment]
Ok, https://github.com/syoyo/tinygltf/pull/451 adds that. BUT it passes, and it turns out it's not part of the mingw build itself which is defining this macro. 

It must be coming from one of the dependencies in the project. (There's some hefty ones there, like Qt and GDAL which have hundreds of dependencies themselves). A quick code scan on github shows a number of projects defining this macro: https://github.com/search?q=%22%23Define+strict+%22&type=code&p=1

More details here: https://learn.microsoft.com/en-au/windows/win32/winprog/enabling-strict?redirectedfrom=MSDN

**Comment by syoyo** [comment]
I see.

I think it'd be better to add suffix(or prefix) to enum identifier or only capitalize the first character to avoid potential conflict of any macro names. How do you think?


```
  typedef enum {
    STRICTNESS_PERMISSIVE,
    STRICTNESS_STRICT,
  } ParseStrictness;

  // or

  typedef enum {
    Permissive,
    Strict,
  } ParseStrictness;

```

**Comment by nyalldawson** [comment]
@syoyo 
> I think it'd be better to add suffix(or prefix) to enum identifier or only capitalize the first character to avoid potential conflict of any macro names. How do you think?

Ok, done. I've gone with the capitalization change to avoid any risk.

**Comment by syoyo** [comment]
Brilliant! Thanks! Merged! > I've gone with the capitalization change to avoid any risk.

**Pull request merged**
