### PR TITLE
Move semantics

### PR DESCRIPTION
**Pull request by Selmar**
Implement default noexcept move constructor/operator, as discussed in #197 

I don't have a C++11 compiler available, but godbolt seemed happy.

@jrkoonce I guess this works, then?

### CODE REVIEW

**Comment by Selmar** [comment]
So apparently compilation success depends on the gcc version. I guess this is the issue you ran into, @jrkoonce .

**Comment by Selmar** [comment]
probably relevant:

https://stackoverflow.com/questions/20610658/defaulted-move-assignment-cannot-be-explicitly-noexcept-if-a-member-has-a-non-tr

**Comment by syoyo** [comment]
Travis error happens when compiling unit test with clang++.

When I modify travis script to show clang version,

```
0.28s$ clang++ -v
clang version 7.0.0 (tags/RELEASE_700/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang-7.0.0/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

it looks compilation error is due to using gcc 4.8 headers(gnustl).
When I compile unit tester with gcc 4.9 STL headers or `-std=libc++`, error does not happen.

So, the code itself should be ok.

**Comment by syoyo** [comment]
Compilation error happens with gcc 4.8. I can reproduce it with CentOS7's default gcc(4.8)

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 
$ make
g++   -std=c++11 -g -O0 -o loader_example loader_example.cc 
In file included from loader_example.cc:7:0:
tiny_gltf.h:275:3: error: function ‘tinygltf::Value::Value(tinygltf::Value&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘tinygltf::Value::Value(tinygltf::Value&&)’
   Value(Value &&) noexcept = default;
   ^
tiny_gltf.h:277:10: error: function ‘tinygltf::Value& tinygltf::Value::operator=(tinygltf::Value&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘tinygltf::Value& tinygltf::Value::operator=(tinygltf::Value&&)’
   Value &operator=(Value &&) noexcept = default;
          ^
```

It is known that gcc 4.8 does not fully support C++11. 
Still, I'd like to support old compiler since sometime we have to stick to use gcc 4.8(e.g. compile glTF Maya plugin on CentOS7 platform). Possible solution is to use ifdef's.

**Comment by jrkoonce** [comment]
Visual Studio 2017 compiles the changes fine.  Last I read, it depends on if the STL implementation defines a particular method we are using on std::vector as noexcept or not, and vendor's are allowed to define it either way.  Older versions that don't have it noexcept cause the problem I think.  OR I'm completely fool of s*it. :)

Simplest solution may be to use a macro NOEXCEPT and have it defined to "noexcept" when you enable the exception specification, and defined to nothing when you don't, then set it based on STL implementation or compiler version.  And of course replace all "noexcept" with "NOEXCEPT" macro.

I am usually not a macro fan, but you can also make a macro to explicitly define the copy/move/assignment operators as default impls.  I would personally add the destructor to it so they are also explicitly defined as defaulted too.  I'd do that so if someone adds a destructor it wouldn't compile, or they at least get a hint that defining the destructor would have unintended consequences.

#if USE_NOEXECEPT
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#50 
#define DEFAULT_METHODS(x) ~x() = default; x(const x&) = default; x(x&&) NOEXCEPT = default; ...

class Value
{
public:
DEFAULT_METHODS(Value)
};

**Comment by syoyo** [comment]
> Older versions that don't have it noexcept cause the problem I think.

For gcc, according to gcc4.8's C++11 status

https://gcc.gnu.org/gcc-4.8/cxx0x_status.html

> Allowing move constructors to throw [noexcept] | N3050 | Yes (core language only)

`noexcept` support is only in language level, so GNU STL implementation is not complete(it may have different signature without `noexcept`)

**Comment by syoyo** [comment]
@Selmar thanks!

> Travis says the previously failing build it is using the gcc compiler version 4.9

Actually, the failure was caused in clang7 + gcc 5.4 STL combination.

https://travis-ci.org/syoyo/tinygltf/jobs/601353390#L479

So there was another reason for the compilation error.
I have also confirmed the build gets ok with gcc 4.8(CentOS7)

After some extra tests(e.g. build `basic` viewer), I will merge this PR.

**Comment by Selmar** [comment]
> Actually, the failure was caused in clang7 + gcc 5.4 STL combination.
> 
> https://travis-ci.org/syoyo/tinygltf/jobs/601353390#L479
> 
> So there was another reason for the compilation error.

I don't understand why this one wouldn't still fail, then.

**Comment by syoyo** [comment]
Tested with some examples and works file, so merged.

**Pull request merged**
