### PR TITLE
Upgraded dear imgui and ImGuizmo to the latest version

### PR DESCRIPTION
**Pull request by Ybalrid**
Upgraded ImGui and ImGuizmo to their lattest version on GitHub.

Fixed the changes on the implementation on "btgui" (some function signature now permit you to pass a `void*  "user context" to functions) 

The Gizmo feels a little bit nicer to use in the latest version

Signed-off-by: Arthur Brainville (Ybalrid) <ybalrid@ybalrid.info>

### CODE REVIEW

**Comment by Ybalrid** [comment]
(I will send you theses changes for NanoSG too)

**Comment by Ybalrid** [comment]
Mh, don't merge it just yet, there's a little bug I need to squash

**Comment by Ybalrid** [comment]
This is good to go now

**Comment by syoyo** [comment]
Cool! Merged!

**Pull request merged**
