### PR TITLE
Small security and overflow patch

### PR DESCRIPTION
**Pull request by rhiskey**
Fixed issues with printing via `sprintf` and `header_and_json` file size.

### CODE REVIEW

**Comment by rhiskey** [comment]
Please review if this change takes place:

https://github.com/syoyo/tinygltf/pull/467/commits/1c6f6efafcf10f8a2981a1316253e16a5a2ed546

**Comment by rhiskey** [comment]
Reverted back original limits and added `#undef max` (in case of Windows)

**Comment by syoyo** [comment]
@rhiskey Thanks!

For annoying MSVC min/max macro issue, the best way is wrapping it with braces(it works also for non-windows platform)

```
(std::max)(a, b)

(std::numeric_limits<float>::max)()
```

**Comment by rhiskey** [comment]
> @rhiskey Thanks!
> 
> For annoying MSVC min/max macro issue, the best way is wrapping it with braces(it works also for non-windows platform)
> 
> ```
> (std::max)(a, b)
> 
> (std::numeric_limits<float>::max)()
> ```

Thank you very much for taking the time and telling me about this method. Added a new commit with MSVC "anti-annoying fix".

**Comment by syoyo** [comment]
For `sprintf_s`,  as CI test fails, it is not guaranteed  to be available when  `__STDC_LIB_EXT1__ ` is not defined.

https://en.cppreference.com/w/c/io/fprintf

> As with all bounds-checked functions, printf_s , fprintf_s, sprintf_s, and snprintf_s are only guaranteed to be available if __STDC_LIB_EXT1__ is defined by the implementation and if the user defines __STDC_WANT_LIB_EXT1__ to the integer constant 1 before including [<stdio.h>](https://en.cppreference.com/w/c/io).

So please use `snprintf`, which is available from C99

https://stackoverflow.com/questions/59948723/how-to-use-sprintf-s-for-linux-c

**Comment by rhiskey** [comment]
I really appreciate your attention. Hope this small fix will be fine

**Comment by syoyo** [comment]
@rhiskey Thanks! Merged!

**Pull request merged**
